x-service: &common-dev-test
  build:
    context: .
    target: build
  volumes:
    - .:/src
  working_dir: /src

version: "3.6"
services:
  prod:
    image: dhis2/im-users:${IMAGE_TAG:-latest}
    build: .
    ports:
      - "8080:8080"

  test:
    <<: *common-dev-test
    command: /bin/sh -c 'go test -v ./...'

  dev-test:
    <<: *common-dev-test
    command: reflex -r "Dockerfile|\.go|\.yml$$" -s -- sh -c "go test -v ./..."

  dev:
    <<: *common-dev-test
    ports:
      - "8080:8080"
    command: reflex -r "Dockerfile|\.go|\.yml$$" -s -- sh -c "go run ./cmd/serve"
