apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
    - image: dhis2/im-users
deploy:
  helm:
    releases:
      - name: im-users-feature
        namespace: instance-manager-feature
        chartPath: helm/chart
        artifactOverrides:
          image: dhis2/im-users
        imageStrategy:
          helm: { }
        useHelmSecrets: true
        valuesFiles:
          - helm/data/secrets/feature/values.yaml
          - helm/data/values/feature/values.yaml

      - name: im-user-postgresql-feature
        namespace: instance-manager-feature
        remoteChart: postgresql
        #version: ???
        repo: https://charts.bitnami.com/bitnami
        useHelmSecrets: true
        valuesFiles:
          - helm/data/secrets/feature/postgresql.yaml

      - name: im-user-redis-feature
        namespace: instance-manager-feature
        remoteChart: redis
        #version: ???
        repo: https://charts.bitnami.com/bitnami
        setValues:
          architecture: standalone
          auth:
            enabled: false
