apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
    - image: dhis2/im-users
  tagPolicy:
    inputDigest: { }
deploy:
  statusCheckDeadlineSeconds: 240
  helm:
    releases:
      - name: im-user-postgresql-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .ENVIRONMENT }}
        createNamespace: true
        remoteChart: postgresql
        repo: https://charts.bitnami.com/bitnami
        version: 11.0.4
        useHelmSecrets: true
        valuesFiles:
          - helm/data/secrets/{{ .ENVIRONMENT }}/postgresql.yaml

      - name: im-user-redis-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .ENVIRONMENT }}
        createNamespace: true
        remoteChart: redis
        repo: https://charts.bitnami.com/bitnami
        version: 16.4.0
        setValues:
          architecture: standalone
          auth:
            enabled: false

      - name: im-user-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .ENVIRONMENT }}
        createNamespace: true
        chartPath: helm/chart
        artifactOverrides:
          image: dhis2/im-users
        imageStrategy:
          helm: { }
        useHelmSecrets: true
        valuesFiles:
          - helm/data/secrets/{{ .ENVIRONMENT }}/values.yaml
          - helm/data/values/{{ .ENVIRONMENT }}/values.yaml
