// Code generated by go-swagger; DO NOT EDIT.

package administrative

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new administrative API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for administrative API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	PostGroups(params *PostGroupsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostGroupsCreated, error)

	PostGroupsGroupIDClusterConfiguration(params *PostGroupsGroupIDClusterConfigurationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostGroupsGroupIDClusterConfigurationCreated, error)

	PostUsersUserIDGroupsGroupID(params *PostUsersUserIDGroupsGroupIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostUsersUserIDGroupsGroupIDCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  PostGroups creates group

  Posting name and hostname...
*/
func (a *Client) PostGroups(params *PostGroupsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostGroupsCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostGroupsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostGroups",
		Method:             "POST",
		PathPattern:        "/groups",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostGroupsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostGroupsCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostGroups: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PostGroupsGroupIDClusterConfiguration adds cluster configuration to a group

  Add cluster configuration to a group...
*/
func (a *Client) PostGroupsGroupIDClusterConfiguration(params *PostGroupsGroupIDClusterConfigurationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostGroupsGroupIDClusterConfigurationCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostGroupsGroupIDClusterConfigurationParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostGroupsGroupIDClusterConfiguration",
		Method:             "POST",
		PathPattern:        "/groups/{groupId}/cluster-configuration",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"multipart/form-data"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostGroupsGroupIDClusterConfigurationReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostGroupsGroupIDClusterConfigurationCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostGroupsGroupIDClusterConfiguration: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PostUsersUserIDGroupsGroupID adds user to group

  Add user to group
*/
func (a *Client) PostUsersUserIDGroupsGroupID(params *PostUsersUserIDGroupsGroupIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostUsersUserIDGroupsGroupIDCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostUsersUserIDGroupsGroupIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostUsersUserIDGroupsGroupID",
		Method:             "POST",
		PathPattern:        "/users/{userId}/groups/{groupId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostUsersUserIDGroupsGroupIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostUsersUserIDGroupsGroupIDCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostUsersUserIDGroupsGroupID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
