// Code generated by go-swagger; DO NOT EDIT.

package administrative

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostGroupsGroupIDClusterConfigurationParams creates a new PostGroupsGroupIDClusterConfigurationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostGroupsGroupIDClusterConfigurationParams() *PostGroupsGroupIDClusterConfigurationParams {
	return &PostGroupsGroupIDClusterConfigurationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostGroupsGroupIDClusterConfigurationParamsWithTimeout creates a new PostGroupsGroupIDClusterConfigurationParams object
// with the ability to set a timeout on a request.
func NewPostGroupsGroupIDClusterConfigurationParamsWithTimeout(timeout time.Duration) *PostGroupsGroupIDClusterConfigurationParams {
	return &PostGroupsGroupIDClusterConfigurationParams{
		timeout: timeout,
	}
}

// NewPostGroupsGroupIDClusterConfigurationParamsWithContext creates a new PostGroupsGroupIDClusterConfigurationParams object
// with the ability to set a context for a request.
func NewPostGroupsGroupIDClusterConfigurationParamsWithContext(ctx context.Context) *PostGroupsGroupIDClusterConfigurationParams {
	return &PostGroupsGroupIDClusterConfigurationParams{
		Context: ctx,
	}
}

// NewPostGroupsGroupIDClusterConfigurationParamsWithHTTPClient creates a new PostGroupsGroupIDClusterConfigurationParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostGroupsGroupIDClusterConfigurationParamsWithHTTPClient(client *http.Client) *PostGroupsGroupIDClusterConfigurationParams {
	return &PostGroupsGroupIDClusterConfigurationParams{
		HTTPClient: client,
	}
}

/* PostGroupsGroupIDClusterConfigurationParams contains all the parameters to send to the API endpoint
   for the post groups group ID cluster configuration operation.

   Typically these are written to a http.Request.
*/
type PostGroupsGroupIDClusterConfigurationParams struct {

	/* GroupID.

	   Group ID
	*/
	GroupID string

	/* KubernetesConfiguration.

	   SOPS encrypted Kubernetes configuration file
	*/
	KubernetesConfiguration runtime.NamedReadCloser

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post groups group ID cluster configuration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostGroupsGroupIDClusterConfigurationParams) WithDefaults() *PostGroupsGroupIDClusterConfigurationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post groups group ID cluster configuration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostGroupsGroupIDClusterConfigurationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post groups group ID cluster configuration params
func (o *PostGroupsGroupIDClusterConfigurationParams) WithTimeout(timeout time.Duration) *PostGroupsGroupIDClusterConfigurationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post groups group ID cluster configuration params
func (o *PostGroupsGroupIDClusterConfigurationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post groups group ID cluster configuration params
func (o *PostGroupsGroupIDClusterConfigurationParams) WithContext(ctx context.Context) *PostGroupsGroupIDClusterConfigurationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post groups group ID cluster configuration params
func (o *PostGroupsGroupIDClusterConfigurationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post groups group ID cluster configuration params
func (o *PostGroupsGroupIDClusterConfigurationParams) WithHTTPClient(client *http.Client) *PostGroupsGroupIDClusterConfigurationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post groups group ID cluster configuration params
func (o *PostGroupsGroupIDClusterConfigurationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroupID adds the groupID to the post groups group ID cluster configuration params
func (o *PostGroupsGroupIDClusterConfigurationParams) WithGroupID(groupID string) *PostGroupsGroupIDClusterConfigurationParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the post groups group ID cluster configuration params
func (o *PostGroupsGroupIDClusterConfigurationParams) SetGroupID(groupID string) {
	o.GroupID = groupID
}

// WithKubernetesConfiguration adds the kubernetesConfiguration to the post groups group ID cluster configuration params
func (o *PostGroupsGroupIDClusterConfigurationParams) WithKubernetesConfiguration(kubernetesConfiguration runtime.NamedReadCloser) *PostGroupsGroupIDClusterConfigurationParams {
	o.SetKubernetesConfiguration(kubernetesConfiguration)
	return o
}

// SetKubernetesConfiguration adds the kubernetesConfiguration to the post groups group ID cluster configuration params
func (o *PostGroupsGroupIDClusterConfigurationParams) SetKubernetesConfiguration(kubernetesConfiguration runtime.NamedReadCloser) {
	o.KubernetesConfiguration = kubernetesConfiguration
}

// WriteToRequest writes these params to a swagger request
func (o *PostGroupsGroupIDClusterConfigurationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param groupId
	if err := r.SetPathParam("groupId", o.GroupID); err != nil {
		return err
	}
	// form file param kubernetesConfiguration
	if err := r.SetFileParam("kubernetesConfiguration", o.KubernetesConfiguration); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
