// Code generated by go-swagger; DO NOT EDIT.

package administrative

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostUsersUserIDGroupsGroupIDParams creates a new PostUsersUserIDGroupsGroupIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostUsersUserIDGroupsGroupIDParams() *PostUsersUserIDGroupsGroupIDParams {
	return &PostUsersUserIDGroupsGroupIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostUsersUserIDGroupsGroupIDParamsWithTimeout creates a new PostUsersUserIDGroupsGroupIDParams object
// with the ability to set a timeout on a request.
func NewPostUsersUserIDGroupsGroupIDParamsWithTimeout(timeout time.Duration) *PostUsersUserIDGroupsGroupIDParams {
	return &PostUsersUserIDGroupsGroupIDParams{
		timeout: timeout,
	}
}

// NewPostUsersUserIDGroupsGroupIDParamsWithContext creates a new PostUsersUserIDGroupsGroupIDParams object
// with the ability to set a context for a request.
func NewPostUsersUserIDGroupsGroupIDParamsWithContext(ctx context.Context) *PostUsersUserIDGroupsGroupIDParams {
	return &PostUsersUserIDGroupsGroupIDParams{
		Context: ctx,
	}
}

// NewPostUsersUserIDGroupsGroupIDParamsWithHTTPClient creates a new PostUsersUserIDGroupsGroupIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostUsersUserIDGroupsGroupIDParamsWithHTTPClient(client *http.Client) *PostUsersUserIDGroupsGroupIDParams {
	return &PostUsersUserIDGroupsGroupIDParams{
		HTTPClient: client,
	}
}

/* PostUsersUserIDGroupsGroupIDParams contains all the parameters to send to the API endpoint
   for the post users user ID groups group ID operation.

   Typically these are written to a http.Request.
*/
type PostUsersUserIDGroupsGroupIDParams struct {

	/* GroupID.

	   Group id
	*/
	GroupID string

	/* UserID.

	   User id
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post users user ID groups group ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostUsersUserIDGroupsGroupIDParams) WithDefaults() *PostUsersUserIDGroupsGroupIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post users user ID groups group ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostUsersUserIDGroupsGroupIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post users user ID groups group ID params
func (o *PostUsersUserIDGroupsGroupIDParams) WithTimeout(timeout time.Duration) *PostUsersUserIDGroupsGroupIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post users user ID groups group ID params
func (o *PostUsersUserIDGroupsGroupIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post users user ID groups group ID params
func (o *PostUsersUserIDGroupsGroupIDParams) WithContext(ctx context.Context) *PostUsersUserIDGroupsGroupIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post users user ID groups group ID params
func (o *PostUsersUserIDGroupsGroupIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post users user ID groups group ID params
func (o *PostUsersUserIDGroupsGroupIDParams) WithHTTPClient(client *http.Client) *PostUsersUserIDGroupsGroupIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post users user ID groups group ID params
func (o *PostUsersUserIDGroupsGroupIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroupID adds the groupID to the post users user ID groups group ID params
func (o *PostUsersUserIDGroupsGroupIDParams) WithGroupID(groupID string) *PostUsersUserIDGroupsGroupIDParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the post users user ID groups group ID params
func (o *PostUsersUserIDGroupsGroupIDParams) SetGroupID(groupID string) {
	o.GroupID = groupID
}

// WithUserID adds the userID to the post users user ID groups group ID params
func (o *PostUsersUserIDGroupsGroupIDParams) WithUserID(userID string) *PostUsersUserIDGroupsGroupIDParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the post users user ID groups group ID params
func (o *PostUsersUserIDGroupsGroupIDParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *PostUsersUserIDGroupsGroupIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param groupId
	if err := r.SetPathParam("groupId", o.GroupID); err != nil {
		return err
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
