// Code generated by go-swagger; DO NOT EDIT.

package administrative

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostUsersUserIDGroupsGroupIDReader is a Reader for the PostUsersUserIDGroupsGroupID structure.
type PostUsersUserIDGroupsGroupIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostUsersUserIDGroupsGroupIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostUsersUserIDGroupsGroupIDCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostUsersUserIDGroupsGroupIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostUsersUserIDGroupsGroupIDCreated creates a PostUsersUserIDGroupsGroupIDCreated with default headers values
func NewPostUsersUserIDGroupsGroupIDCreated() *PostUsersUserIDGroupsGroupIDCreated {
	return &PostUsersUserIDGroupsGroupIDCreated{}
}

/* PostUsersUserIDGroupsGroupIDCreated describes a response with status code 201, with default header values.

Created
*/
type PostUsersUserIDGroupsGroupIDCreated struct {
	Payload string
}

func (o *PostUsersUserIDGroupsGroupIDCreated) Error() string {
	return fmt.Sprintf("[POST /users/{userId}/groups/{groupId}][%d] postUsersUserIdGroupsGroupIdCreated  %+v", 201, o.Payload)
}
func (o *PostUsersUserIDGroupsGroupIDCreated) GetPayload() string {
	return o.Payload
}

func (o *PostUsersUserIDGroupsGroupIDCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostUsersUserIDGroupsGroupIDBadRequest creates a PostUsersUserIDGroupsGroupIDBadRequest with default headers values
func NewPostUsersUserIDGroupsGroupIDBadRequest() *PostUsersUserIDGroupsGroupIDBadRequest {
	return &PostUsersUserIDGroupsGroupIDBadRequest{}
}

/* PostUsersUserIDGroupsGroupIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostUsersUserIDGroupsGroupIDBadRequest struct {
	Payload interface{}
}

func (o *PostUsersUserIDGroupsGroupIDBadRequest) Error() string {
	return fmt.Sprintf("[POST /users/{userId}/groups/{groupId}][%d] postUsersUserIdGroupsGroupIdBadRequest  %+v", 400, o.Payload)
}
func (o *PostUsersUserIDGroupsGroupIDBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *PostUsersUserIDGroupsGroupIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
