// Code generated by go-swagger; DO NOT EDIT.

package administrative

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dhis2-sre/im-users/swagger/client/models"
)

// PostGroupsReader is a Reader for the PostGroups structure.
type PostGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostGroupsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostGroupsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostGroupsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewPostGroupsUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostGroupsCreated creates a PostGroupsCreated with default headers values
func NewPostGroupsCreated() *PostGroupsCreated {
	return &PostGroupsCreated{}
}

/* PostGroupsCreated describes a response with status code 201, with default header values.

Created
*/
type PostGroupsCreated struct {
	Payload *models.DtoGroup
}

func (o *PostGroupsCreated) Error() string {
	return fmt.Sprintf("[POST /groups][%d] postGroupsCreated  %+v", 201, o.Payload)
}
func (o *PostGroupsCreated) GetPayload() *models.DtoGroup {
	return o.Payload
}

func (o *PostGroupsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostGroupsBadRequest creates a PostGroupsBadRequest with default headers values
func NewPostGroupsBadRequest() *PostGroupsBadRequest {
	return &PostGroupsBadRequest{}
}

/* PostGroupsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostGroupsBadRequest struct {
	Payload interface{}
}

func (o *PostGroupsBadRequest) Error() string {
	return fmt.Sprintf("[POST /groups][%d] postGroupsBadRequest  %+v", 400, o.Payload)
}
func (o *PostGroupsBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *PostGroupsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostGroupsForbidden creates a PostGroupsForbidden with default headers values
func NewPostGroupsForbidden() *PostGroupsForbidden {
	return &PostGroupsForbidden{}
}

/* PostGroupsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PostGroupsForbidden struct {
	Payload interface{}
}

func (o *PostGroupsForbidden) Error() string {
	return fmt.Sprintf("[POST /groups][%d] postGroupsForbidden  %+v", 403, o.Payload)
}
func (o *PostGroupsForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *PostGroupsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostGroupsUnsupportedMediaType creates a PostGroupsUnsupportedMediaType with default headers values
func NewPostGroupsUnsupportedMediaType() *PostGroupsUnsupportedMediaType {
	return &PostGroupsUnsupportedMediaType{}
}

/* PostGroupsUnsupportedMediaType describes a response with status code 415, with default header values.

Unsupported Media Type
*/
type PostGroupsUnsupportedMediaType struct {
	Payload interface{}
}

func (o *PostGroupsUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[POST /groups][%d] postGroupsUnsupportedMediaType  %+v", 415, o.Payload)
}
func (o *PostGroupsUnsupportedMediaType) GetPayload() interface{} {
	return o.Payload
}

func (o *PostGroupsUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
