// Code generated by go-swagger; DO NOT EDIT.

package restricted

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGroupsNameToIDNameParams creates a new GetGroupsNameToIDNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetGroupsNameToIDNameParams() *GetGroupsNameToIDNameParams {
	return &GetGroupsNameToIDNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetGroupsNameToIDNameParamsWithTimeout creates a new GetGroupsNameToIDNameParams object
// with the ability to set a timeout on a request.
func NewGetGroupsNameToIDNameParamsWithTimeout(timeout time.Duration) *GetGroupsNameToIDNameParams {
	return &GetGroupsNameToIDNameParams{
		timeout: timeout,
	}
}

// NewGetGroupsNameToIDNameParamsWithContext creates a new GetGroupsNameToIDNameParams object
// with the ability to set a context for a request.
func NewGetGroupsNameToIDNameParamsWithContext(ctx context.Context) *GetGroupsNameToIDNameParams {
	return &GetGroupsNameToIDNameParams{
		Context: ctx,
	}
}

// NewGetGroupsNameToIDNameParamsWithHTTPClient creates a new GetGroupsNameToIDNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetGroupsNameToIDNameParamsWithHTTPClient(client *http.Client) *GetGroupsNameToIDNameParams {
	return &GetGroupsNameToIDNameParams{
		HTTPClient: client,
	}
}

/* GetGroupsNameToIDNameParams contains all the parameters to send to the API endpoint
   for the get groups name to ID name operation.

   Typically these are written to a http.Request.
*/
type GetGroupsNameToIDNameParams struct {

	/* Name.

	   Group name
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get groups name to ID name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupsNameToIDNameParams) WithDefaults() *GetGroupsNameToIDNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get groups name to ID name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupsNameToIDNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get groups name to ID name params
func (o *GetGroupsNameToIDNameParams) WithTimeout(timeout time.Duration) *GetGroupsNameToIDNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get groups name to ID name params
func (o *GetGroupsNameToIDNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get groups name to ID name params
func (o *GetGroupsNameToIDNameParams) WithContext(ctx context.Context) *GetGroupsNameToIDNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get groups name to ID name params
func (o *GetGroupsNameToIDNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get groups name to ID name params
func (o *GetGroupsNameToIDNameParams) WithHTTPClient(client *http.Client) *GetGroupsNameToIDNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get groups name to ID name params
func (o *GetGroupsNameToIDNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get groups name to ID name params
func (o *GetGroupsNameToIDNameParams) WithName(name string) *GetGroupsNameToIDNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get groups name to ID name params
func (o *GetGroupsNameToIDNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetGroupsNameToIDNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
