// Code generated by go-swagger; DO NOT EDIT.

package restricted

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSignoutParams creates a new GetSignoutParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSignoutParams() *GetSignoutParams {
	return &GetSignoutParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSignoutParamsWithTimeout creates a new GetSignoutParams object
// with the ability to set a timeout on a request.
func NewGetSignoutParamsWithTimeout(timeout time.Duration) *GetSignoutParams {
	return &GetSignoutParams{
		timeout: timeout,
	}
}

// NewGetSignoutParamsWithContext creates a new GetSignoutParams object
// with the ability to set a context for a request.
func NewGetSignoutParamsWithContext(ctx context.Context) *GetSignoutParams {
	return &GetSignoutParams{
		Context: ctx,
	}
}

// NewGetSignoutParamsWithHTTPClient creates a new GetSignoutParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSignoutParamsWithHTTPClient(client *http.Client) *GetSignoutParams {
	return &GetSignoutParams{
		HTTPClient: client,
	}
}

/* GetSignoutParams contains all the parameters to send to the API endpoint
   for the get signout operation.

   Typically these are written to a http.Request.
*/
type GetSignoutParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get signout params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSignoutParams) WithDefaults() *GetSignoutParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get signout params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSignoutParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get signout params
func (o *GetSignoutParams) WithTimeout(timeout time.Duration) *GetSignoutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get signout params
func (o *GetSignoutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get signout params
func (o *GetSignoutParams) WithContext(ctx context.Context) *GetSignoutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get signout params
func (o *GetSignoutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get signout params
func (o *GetSignoutParams) WithHTTPClient(client *http.Client) *GetSignoutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get signout params
func (o *GetSignoutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSignoutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
