// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"github.com/dhis2-sre/im-users/internal/middleware"
	"github.com/dhis2-sre/im-users/pkg/config"
	"github.com/dhis2-sre/im-users/pkg/group"
	"github.com/dhis2-sre/im-users/pkg/storage"
	"github.com/dhis2-sre/im-users/pkg/token"
	"github.com/dhis2-sre/im-users/pkg/user"
	"gorm.io/gorm"
	"log"
)

// Injectors from wire.go:

func GetEnvironment() Environment {
	configConfig := config.ProvideConfig()
	client := storage.ProvideRedis(configConfig)
	repository := token.ProvideTokenRepository(client)
	service := token.ProvideTokenService(configConfig, repository)
	handler := token.ProvideHandler(configConfig)
	db := provideDatabase(configConfig)
	userRepository := user.ProvideRepository(db)
	userService := user.ProvideService(userRepository)
	userHandler := user.ProvideHandler(configConfig, userService, service)
	groupRepository := group.ProvideRepository(db)
	groupService := group.ProvideService(groupRepository, userRepository)
	groupHandler := group.ProvideHandler(groupService, userService)
	authenticationMiddleware := middleware.ProvideAuthentication(userService, service)
	authorizationMiddleware := middleware.ProvideAuthorization(userService)
	environment := ProvideEnvironment(configConfig, service, handler, userService, userHandler, groupService, groupHandler, authenticationMiddleware, authorizationMiddleware)
	return environment
}

// wire.go:

type Environment struct {
	Config                   config.Config
	TokenService             token.Service
	TokenHandler             token.Handler
	UserService              user.Service
	UserHandler              user.Handler
	GroupService             group.Service
	GroupHandler             group.Handler
	AuthenticationMiddleware middleware.AuthenticationMiddleware
	AuthorizationMiddleware  middleware.AuthorizationMiddleware
}

func ProvideEnvironment(config2 config.Config,

	tokenService token.Service,
	tokenHandler token.Handler,
	userService user.Service,
	userHandler user.Handler,
	groupService group.Service,
	groupHandler group.Handler,
	authenticationMiddleware middleware.AuthenticationMiddleware,
	authorizationMiddleware middleware.AuthorizationMiddleware,
) Environment {
	return Environment{config2, tokenService,
		tokenHandler,
		userService,
		userHandler,
		groupService,
		groupHandler,
		authenticationMiddleware,
		authorizationMiddleware,
	}
}

func provideDatabase(c config.Config) *gorm.DB {
	database, err := storage.ProvideDatabase(c)
	if err != nil {
		log.Fatalln(err)
	}
	return database
}
