// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoClusterConfiguration dto cluster configuration
//
// swagger:model dto.ClusterConfiguration
type DtoClusterConfiguration struct {

	// group Id
	GroupID int64 `json:"groupId,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// kubernetes configuration
	KubernetesConfiguration []int64 `json:"kubernetesConfiguration"`
}

// Validate validates this dto cluster configuration
func (m *DtoClusterConfiguration) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto cluster configuration based on context it is used
func (m *DtoClusterConfiguration) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoClusterConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoClusterConfiguration) UnmarshalBinary(b []byte) error {
	var res DtoClusterConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
