// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GithubComDhis2SreImUsersPkgUserRefreshTokenRequest github com dhis2 sre im users pkg user refresh token request
//
// swagger:model github.com_dhis2-sre_im-users_pkg_user.RefreshTokenRequest
type GithubComDhis2SreImUsersPkgUserRefreshTokenRequest struct {

	// refresh token
	// Required: true
	RefreshToken *string `json:"refreshToken"`
}

// Validate validates this github com dhis2 sre im users pkg user refresh token request
func (m *GithubComDhis2SreImUsersPkgUserRefreshTokenRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRefreshToken(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComDhis2SreImUsersPkgUserRefreshTokenRequest) validateRefreshToken(formats strfmt.Registry) error {

	if err := validate.Required("refreshToken", "body", m.RefreshToken); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this github com dhis2 sre im users pkg user refresh token request based on context it is used
func (m *GithubComDhis2SreImUsersPkgUserRefreshTokenRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComDhis2SreImUsersPkgUserRefreshTokenRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComDhis2SreImUsersPkgUserRefreshTokenRequest) UnmarshalBinary(b []byte) error {
	var res GithubComDhis2SreImUsersPkgUserRefreshTokenRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
