// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GithubComDhis2SreImUsersPkgUserSignupRequest github com dhis2 sre im users pkg user signup request
//
// swagger:model github.com_dhis2-sre_im-users_pkg_user.SignupRequest
type GithubComDhis2SreImUsersPkgUserSignupRequest struct {

	// email
	// Required: true
	Email *string `json:"email"`

	// password
	// Required: true
	Password *string `json:"password"`
}

// Validate validates this github com dhis2 sre im users pkg user signup request
func (m *GithubComDhis2SreImUsersPkgUserSignupRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComDhis2SreImUsersPkgUserSignupRequest) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("email", "body", m.Email); err != nil {
		return err
	}

	return nil
}

func (m *GithubComDhis2SreImUsersPkgUserSignupRequest) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this github com dhis2 sre im users pkg user signup request based on context it is used
func (m *GithubComDhis2SreImUsersPkgUserSignupRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComDhis2SreImUsersPkgUserSignupRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComDhis2SreImUsersPkgUserSignupRequest) UnmarshalBinary(b []byte) error {
	var res GithubComDhis2SreImUsersPkgUserSignupRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
