// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetFindbyidIDParams creates a new GetFindbyidIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFindbyidIDParams() *GetFindbyidIDParams {
	return &GetFindbyidIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetFindbyidIDParamsWithTimeout creates a new GetFindbyidIDParams object
// with the ability to set a timeout on a request.
func NewGetFindbyidIDParamsWithTimeout(timeout time.Duration) *GetFindbyidIDParams {
	return &GetFindbyidIDParams{
		timeout: timeout,
	}
}

// NewGetFindbyidIDParamsWithContext creates a new GetFindbyidIDParams object
// with the ability to set a context for a request.
func NewGetFindbyidIDParamsWithContext(ctx context.Context) *GetFindbyidIDParams {
	return &GetFindbyidIDParams{
		Context: ctx,
	}
}

// NewGetFindbyidIDParamsWithHTTPClient creates a new GetFindbyidIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFindbyidIDParamsWithHTTPClient(client *http.Client) *GetFindbyidIDParams {
	return &GetFindbyidIDParams{
		HTTPClient: client,
	}
}

/* GetFindbyidIDParams contains all the parameters to send to the API endpoint
   for the get findbyid ID operation.

   Typically these are written to a http.Request.
*/
type GetFindbyidIDParams struct {

	/* ID.

	   User id
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get findbyid ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFindbyidIDParams) WithDefaults() *GetFindbyidIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get findbyid ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFindbyidIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get findbyid ID params
func (o *GetFindbyidIDParams) WithTimeout(timeout time.Duration) *GetFindbyidIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get findbyid ID params
func (o *GetFindbyidIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get findbyid ID params
func (o *GetFindbyidIDParams) WithContext(ctx context.Context) *GetFindbyidIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get findbyid ID params
func (o *GetFindbyidIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get findbyid ID params
func (o *GetFindbyidIDParams) WithHTTPClient(client *http.Client) *GetFindbyidIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get findbyid ID params
func (o *GetFindbyidIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get findbyid ID params
func (o *GetFindbyidIDParams) WithID(id int64) *GetFindbyidIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get findbyid ID params
func (o *GetFindbyidIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetFindbyidIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
