// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostSigninParams creates a new PostSigninParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostSigninParams() *PostSigninParams {
	return &PostSigninParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostSigninParamsWithTimeout creates a new PostSigninParams object
// with the ability to set a timeout on a request.
func NewPostSigninParamsWithTimeout(timeout time.Duration) *PostSigninParams {
	return &PostSigninParams{
		timeout: timeout,
	}
}

// NewPostSigninParamsWithContext creates a new PostSigninParams object
// with the ability to set a context for a request.
func NewPostSigninParamsWithContext(ctx context.Context) *PostSigninParams {
	return &PostSigninParams{
		Context: ctx,
	}
}

// NewPostSigninParamsWithHTTPClient creates a new PostSigninParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostSigninParamsWithHTTPClient(client *http.Client) *PostSigninParams {
	return &PostSigninParams{
		HTTPClient: client,
	}
}

/* PostSigninParams contains all the parameters to send to the API endpoint
   for the post signin operation.

   Typically these are written to a http.Request.
*/
type PostSigninParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post signin params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostSigninParams) WithDefaults() *PostSigninParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post signin params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostSigninParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post signin params
func (o *PostSigninParams) WithTimeout(timeout time.Duration) *PostSigninParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post signin params
func (o *PostSigninParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post signin params
func (o *PostSigninParams) WithContext(ctx context.Context) *PostSigninParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post signin params
func (o *PostSigninParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post signin params
func (o *PostSigninParams) WithHTTPClient(client *http.Client) *PostSigninParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post signin params
func (o *PostSigninParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostSigninParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
