// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dhis2-sre/im-users/swagger/client/models"
)

// PostSignupReader is a Reader for the PostSignup structure.
type PostSignupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostSignupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostSignupCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostSignupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostSignupCreated creates a PostSignupCreated with default headers values
func NewPostSignupCreated() *PostSignupCreated {
	return &PostSignupCreated{}
}

/* PostSignupCreated describes a response with status code 201, with default header values.

Created
*/
type PostSignupCreated struct {
	Payload *models.DtoUser
}

func (o *PostSignupCreated) Error() string {
	return fmt.Sprintf("[POST /signup][%d] postSignupCreated  %+v", 201, o.Payload)
}
func (o *PostSignupCreated) GetPayload() *models.DtoUser {
	return o.Payload
}

func (o *PostSignupCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoUser)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostSignupBadRequest creates a PostSignupBadRequest with default headers values
func NewPostSignupBadRequest() *PostSignupBadRequest {
	return &PostSignupBadRequest{}
}

/* PostSignupBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostSignupBadRequest struct {
	Payload interface{}
}

func (o *PostSignupBadRequest) Error() string {
	return fmt.Sprintf("[POST /signup][%d] postSignupBadRequest  %+v", 400, o.Payload)
}
func (o *PostSignupBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *PostSignupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
