// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostRefreshReader is a Reader for the PostRefresh structure.
type PostRefreshReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRefreshReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostRefreshCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostRefreshBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostRefreshCreated creates a PostRefreshCreated with default headers values
func NewPostRefreshCreated() *PostRefreshCreated {
	return &PostRefreshCreated{}
}

/* PostRefreshCreated describes a response with status code 201, with default header values.

Created
*/
type PostRefreshCreated struct {
	Payload interface{}
}

func (o *PostRefreshCreated) Error() string {
	return fmt.Sprintf("[POST /refresh][%d] postRefreshCreated  %+v", 201, o.Payload)
}
func (o *PostRefreshCreated) GetPayload() interface{} {
	return o.Payload
}

func (o *PostRefreshCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRefreshBadRequest creates a PostRefreshBadRequest with default headers values
func NewPostRefreshBadRequest() *PostRefreshBadRequest {
	return &PostRefreshBadRequest{}
}

/* PostRefreshBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostRefreshBadRequest struct {
	Payload interface{}
}

func (o *PostRefreshBadRequest) Error() string {
	return fmt.Sprintf("[POST /refresh][%d] postRefreshBadRequest  %+v", 400, o.Payload)
}
func (o *PostRefreshBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *PostRefreshBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
