// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new public API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for public API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetFindbyidID(params *GetFindbyidIDParams, opts ...ClientOption) (*GetFindbyidIDOK, error)

	PostRefresh(params *PostRefreshParams, opts ...ClientOption) (*PostRefreshCreated, error)

	PostSignin(params *PostSigninParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostSigninCreated, error)

	PostSignup(params *PostSignupParams, opts ...ClientOption) (*PostSignupCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetFindbyidID users details by id

  Show user details by id
*/
func (a *Client) GetFindbyidID(params *GetFindbyidIDParams, opts ...ClientOption) (*GetFindbyidIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetFindbyidIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetFindbyidID",
		Method:             "GET",
		PathPattern:        "/findbyid/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetFindbyidIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetFindbyidIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetFindbyidID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PostRefresh refreshes tokens

  Post a refresh token and this endpoint will return a fresh set of tokens
*/
func (a *Client) PostRefresh(params *PostRefreshParams, opts ...ClientOption) (*PostRefreshCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostRefreshParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostRefresh",
		Method:             "POST",
		PathPattern:        "/refresh",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostRefreshReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostRefreshCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostRefresh: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PostSignin users sign in

  Classic basic http auth...
*/
func (a *Client) PostSignin(params *PostSigninParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostSigninCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostSigninParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostSignin",
		Method:             "POST",
		PathPattern:        "/signin",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostSigninReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostSigninCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostSignin: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PostSignup users sign in

  Posting username (email) and password... And user is returned
*/
func (a *Client) PostSignup(params *PostSignupParams, opts ...ClientOption) (*PostSignupCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostSignupParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostSignup",
		Method:             "POST",
		PathPattern:        "/signup",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostSignupReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostSignupCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostSignup: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
