// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAddClusterConfigurationToGroupParams creates a new AddClusterConfigurationToGroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddClusterConfigurationToGroupParams() *AddClusterConfigurationToGroupParams {
	return &AddClusterConfigurationToGroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddClusterConfigurationToGroupParamsWithTimeout creates a new AddClusterConfigurationToGroupParams object
// with the ability to set a timeout on a request.
func NewAddClusterConfigurationToGroupParamsWithTimeout(timeout time.Duration) *AddClusterConfigurationToGroupParams {
	return &AddClusterConfigurationToGroupParams{
		timeout: timeout,
	}
}

// NewAddClusterConfigurationToGroupParamsWithContext creates a new AddClusterConfigurationToGroupParams object
// with the ability to set a context for a request.
func NewAddClusterConfigurationToGroupParamsWithContext(ctx context.Context) *AddClusterConfigurationToGroupParams {
	return &AddClusterConfigurationToGroupParams{
		Context: ctx,
	}
}

// NewAddClusterConfigurationToGroupParamsWithHTTPClient creates a new AddClusterConfigurationToGroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddClusterConfigurationToGroupParamsWithHTTPClient(client *http.Client) *AddClusterConfigurationToGroupParams {
	return &AddClusterConfigurationToGroupParams{
		HTTPClient: client,
	}
}

/* AddClusterConfigurationToGroupParams contains all the parameters to send to the API endpoint
   for the add cluster configuration to group operation.

   Typically these are written to a http.Request.
*/
type AddClusterConfigurationToGroupParams struct {

	/* Body.

	   SOPS encrypted Kubernetes configuration file
	*/
	Body runtime.NamedReadCloser

	// Group.
	Group string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add cluster configuration to group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddClusterConfigurationToGroupParams) WithDefaults() *AddClusterConfigurationToGroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add cluster configuration to group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddClusterConfigurationToGroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add cluster configuration to group params
func (o *AddClusterConfigurationToGroupParams) WithTimeout(timeout time.Duration) *AddClusterConfigurationToGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add cluster configuration to group params
func (o *AddClusterConfigurationToGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add cluster configuration to group params
func (o *AddClusterConfigurationToGroupParams) WithContext(ctx context.Context) *AddClusterConfigurationToGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add cluster configuration to group params
func (o *AddClusterConfigurationToGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add cluster configuration to group params
func (o *AddClusterConfigurationToGroupParams) WithHTTPClient(client *http.Client) *AddClusterConfigurationToGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add cluster configuration to group params
func (o *AddClusterConfigurationToGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add cluster configuration to group params
func (o *AddClusterConfigurationToGroupParams) WithBody(body runtime.NamedReadCloser) *AddClusterConfigurationToGroupParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add cluster configuration to group params
func (o *AddClusterConfigurationToGroupParams) SetBody(body runtime.NamedReadCloser) {
	o.Body = body
}

// WithGroup adds the group to the add cluster configuration to group params
func (o *AddClusterConfigurationToGroupParams) WithGroup(group string) *AddClusterConfigurationToGroupParams {
	o.SetGroup(group)
	return o
}

// SetGroup adds the group to the add cluster configuration to group params
func (o *AddClusterConfigurationToGroupParams) SetGroup(group string) {
	o.Group = group
}

// WriteToRequest writes these params to a swagger request
func (o *AddClusterConfigurationToGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	// form file param Body
	if err := r.SetFileParam("Body", o.Body); err != nil {
		return err
	}

	// path param group
	if err := r.SetPathParam("group", o.Group); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
