// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewFindUserByIDParams creates a new FindUserByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindUserByIDParams() *FindUserByIDParams {
	return &FindUserByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindUserByIDParamsWithTimeout creates a new FindUserByIDParams object
// with the ability to set a timeout on a request.
func NewFindUserByIDParamsWithTimeout(timeout time.Duration) *FindUserByIDParams {
	return &FindUserByIDParams{
		timeout: timeout,
	}
}

// NewFindUserByIDParamsWithContext creates a new FindUserByIDParams object
// with the ability to set a context for a request.
func NewFindUserByIDParamsWithContext(ctx context.Context) *FindUserByIDParams {
	return &FindUserByIDParams{
		Context: ctx,
	}
}

// NewFindUserByIDParamsWithHTTPClient creates a new FindUserByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindUserByIDParamsWithHTTPClient(client *http.Client) *FindUserByIDParams {
	return &FindUserByIDParams{
		HTTPClient: client,
	}
}

/* FindUserByIDParams contains all the parameters to send to the API endpoint
   for the find user by Id operation.

   Typically these are written to a http.Request.
*/
type FindUserByIDParams struct {

	// ID.
	//
	// Format: uint64
	ID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find user by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindUserByIDParams) WithDefaults() *FindUserByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find user by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindUserByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find user by Id params
func (o *FindUserByIDParams) WithTimeout(timeout time.Duration) *FindUserByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find user by Id params
func (o *FindUserByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find user by Id params
func (o *FindUserByIDParams) WithContext(ctx context.Context) *FindUserByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find user by Id params
func (o *FindUserByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find user by Id params
func (o *FindUserByIDParams) WithHTTPClient(client *http.Client) *FindUserByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find user by Id params
func (o *FindUserByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the find user by Id params
func (o *FindUserByIDParams) WithID(id uint64) *FindUserByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the find user by Id params
func (o *FindUserByIDParams) SetID(id uint64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *FindUserByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatUint64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
