// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewFindGroupByIDParams creates a new FindGroupByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindGroupByIDParams() *FindGroupByIDParams {
	return &FindGroupByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindGroupByIDParamsWithTimeout creates a new FindGroupByIDParams object
// with the ability to set a timeout on a request.
func NewFindGroupByIDParamsWithTimeout(timeout time.Duration) *FindGroupByIDParams {
	return &FindGroupByIDParams{
		timeout: timeout,
	}
}

// NewFindGroupByIDParamsWithContext creates a new FindGroupByIDParams object
// with the ability to set a context for a request.
func NewFindGroupByIDParamsWithContext(ctx context.Context) *FindGroupByIDParams {
	return &FindGroupByIDParams{
		Context: ctx,
	}
}

// NewFindGroupByIDParamsWithHTTPClient creates a new FindGroupByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindGroupByIDParamsWithHTTPClient(client *http.Client) *FindGroupByIDParams {
	return &FindGroupByIDParams{
		HTTPClient: client,
	}
}

/* FindGroupByIDParams contains all the parameters to send to the API endpoint
   for the find group by Id operation.

   Typically these are written to a http.Request.
*/
type FindGroupByIDParams struct {

	// ID.
	//
	// Format: uint64
	ID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find group by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindGroupByIDParams) WithDefaults() *FindGroupByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find group by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindGroupByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find group by Id params
func (o *FindGroupByIDParams) WithTimeout(timeout time.Duration) *FindGroupByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find group by Id params
func (o *FindGroupByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find group by Id params
func (o *FindGroupByIDParams) WithContext(ctx context.Context) *FindGroupByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find group by Id params
func (o *FindGroupByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find group by Id params
func (o *FindGroupByIDParams) WithHTTPClient(client *http.Client) *FindGroupByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find group by Id params
func (o *FindGroupByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the find group by Id params
func (o *FindGroupByIDParams) WithID(id uint64) *FindGroupByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the find group by Id params
func (o *FindGroupByIDParams) SetID(id uint64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *FindGroupByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatUint64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
