// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dhis2-sre/im-user/swagger/sdk/models"
)

// FindGroupByNameReader is a Reader for the FindGroupByName structure.
type FindGroupByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindGroupByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindGroupByNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewFindGroupByNameUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewFindGroupByNameForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewFindGroupByNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewFindGroupByNameUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewFindGroupByNameOK creates a FindGroupByNameOK with default headers values
func NewFindGroupByNameOK() *FindGroupByNameOK {
	return &FindGroupByNameOK{}
}

/* FindGroupByNameOK describes a response with status code 200, with default header values.

Group
*/
type FindGroupByNameOK struct {
	Payload *models.Group
}

func (o *FindGroupByNameOK) Error() string {
	return fmt.Sprintf("[GET /groups/{name}][%d] findGroupByNameOK  %+v", 200, o.Payload)
}
func (o *FindGroupByNameOK) GetPayload() *models.Group {
	return o.Payload
}

func (o *FindGroupByNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Group)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindGroupByNameUnauthorized creates a FindGroupByNameUnauthorized with default headers values
func NewFindGroupByNameUnauthorized() *FindGroupByNameUnauthorized {
	return &FindGroupByNameUnauthorized{}
}

/* FindGroupByNameUnauthorized describes a response with status code 401, with default header values.

FindGroupByNameUnauthorized find group by name unauthorized
*/
type FindGroupByNameUnauthorized struct {
}

func (o *FindGroupByNameUnauthorized) Error() string {
	return fmt.Sprintf("[GET /groups/{name}][%d] findGroupByNameUnauthorized ", 401)
}

func (o *FindGroupByNameUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewFindGroupByNameForbidden creates a FindGroupByNameForbidden with default headers values
func NewFindGroupByNameForbidden() *FindGroupByNameForbidden {
	return &FindGroupByNameForbidden{}
}

/* FindGroupByNameForbidden describes a response with status code 403, with default header values.

FindGroupByNameForbidden find group by name forbidden
*/
type FindGroupByNameForbidden struct {
}

func (o *FindGroupByNameForbidden) Error() string {
	return fmt.Sprintf("[GET /groups/{name}][%d] findGroupByNameForbidden ", 403)
}

func (o *FindGroupByNameForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewFindGroupByNameNotFound creates a FindGroupByNameNotFound with default headers values
func NewFindGroupByNameNotFound() *FindGroupByNameNotFound {
	return &FindGroupByNameNotFound{}
}

/* FindGroupByNameNotFound describes a response with status code 404, with default header values.

FindGroupByNameNotFound find group by name not found
*/
type FindGroupByNameNotFound struct {
}

func (o *FindGroupByNameNotFound) Error() string {
	return fmt.Sprintf("[GET /groups/{name}][%d] findGroupByNameNotFound ", 404)
}

func (o *FindGroupByNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewFindGroupByNameUnsupportedMediaType creates a FindGroupByNameUnsupportedMediaType with default headers values
func NewFindGroupByNameUnsupportedMediaType() *FindGroupByNameUnsupportedMediaType {
	return &FindGroupByNameUnsupportedMediaType{}
}

/* FindGroupByNameUnsupportedMediaType describes a response with status code 415, with default header values.

FindGroupByNameUnsupportedMediaType find group by name unsupported media type
*/
type FindGroupByNameUnsupportedMediaType struct {
}

func (o *FindGroupByNameUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[GET /groups/{name}][%d] findGroupByNameUnsupportedMediaType ", 415)
}

func (o *FindGroupByNameUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
