// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGroupNameToIDParams creates a new GroupNameToIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGroupNameToIDParams() *GroupNameToIDParams {
	return &GroupNameToIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGroupNameToIDParamsWithTimeout creates a new GroupNameToIDParams object
// with the ability to set a timeout on a request.
func NewGroupNameToIDParamsWithTimeout(timeout time.Duration) *GroupNameToIDParams {
	return &GroupNameToIDParams{
		timeout: timeout,
	}
}

// NewGroupNameToIDParamsWithContext creates a new GroupNameToIDParams object
// with the ability to set a context for a request.
func NewGroupNameToIDParamsWithContext(ctx context.Context) *GroupNameToIDParams {
	return &GroupNameToIDParams{
		Context: ctx,
	}
}

// NewGroupNameToIDParamsWithHTTPClient creates a new GroupNameToIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGroupNameToIDParamsWithHTTPClient(client *http.Client) *GroupNameToIDParams {
	return &GroupNameToIDParams{
		HTTPClient: client,
	}
}

/* GroupNameToIDParams contains all the parameters to send to the API endpoint
   for the group name to Id operation.

   Typically these are written to a http.Request.
*/
type GroupNameToIDParams struct {

	// Name.
	//
	// Format: uint64
	Name uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the group name to Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GroupNameToIDParams) WithDefaults() *GroupNameToIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the group name to Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GroupNameToIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the group name to Id params
func (o *GroupNameToIDParams) WithTimeout(timeout time.Duration) *GroupNameToIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the group name to Id params
func (o *GroupNameToIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the group name to Id params
func (o *GroupNameToIDParams) WithContext(ctx context.Context) *GroupNameToIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the group name to Id params
func (o *GroupNameToIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the group name to Id params
func (o *GroupNameToIDParams) WithHTTPClient(client *http.Client) *GroupNameToIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the group name to Id params
func (o *GroupNameToIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the group name to Id params
func (o *GroupNameToIDParams) WithName(name uint64) *GroupNameToIDParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the group name to Id params
func (o *GroupNameToIDParams) SetName(name uint64) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GroupNameToIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", swag.FormatUint64(o.Name)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
