// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGroupAddUserToGroupParams creates a new GroupAddUserToGroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGroupAddUserToGroupParams() *GroupAddUserToGroupParams {
	return &GroupAddUserToGroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGroupAddUserToGroupParamsWithTimeout creates a new GroupAddUserToGroupParams object
// with the ability to set a timeout on a request.
func NewGroupAddUserToGroupParamsWithTimeout(timeout time.Duration) *GroupAddUserToGroupParams {
	return &GroupAddUserToGroupParams{
		timeout: timeout,
	}
}

// NewGroupAddUserToGroupParamsWithContext creates a new GroupAddUserToGroupParams object
// with the ability to set a context for a request.
func NewGroupAddUserToGroupParamsWithContext(ctx context.Context) *GroupAddUserToGroupParams {
	return &GroupAddUserToGroupParams{
		Context: ctx,
	}
}

// NewGroupAddUserToGroupParamsWithHTTPClient creates a new GroupAddUserToGroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewGroupAddUserToGroupParamsWithHTTPClient(client *http.Client) *GroupAddUserToGroupParams {
	return &GroupAddUserToGroupParams{
		HTTPClient: client,
	}
}

/* GroupAddUserToGroupParams contains all the parameters to send to the API endpoint
   for the group add user to group operation.

   Typically these are written to a http.Request.
*/
type GroupAddUserToGroupParams struct {

	// GroupID.
	//
	// Format: uint64
	GroupID uint64

	// UserID.
	//
	// Format: uint64
	UserID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the group add user to group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GroupAddUserToGroupParams) WithDefaults() *GroupAddUserToGroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the group add user to group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GroupAddUserToGroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the group add user to group params
func (o *GroupAddUserToGroupParams) WithTimeout(timeout time.Duration) *GroupAddUserToGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the group add user to group params
func (o *GroupAddUserToGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the group add user to group params
func (o *GroupAddUserToGroupParams) WithContext(ctx context.Context) *GroupAddUserToGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the group add user to group params
func (o *GroupAddUserToGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the group add user to group params
func (o *GroupAddUserToGroupParams) WithHTTPClient(client *http.Client) *GroupAddUserToGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the group add user to group params
func (o *GroupAddUserToGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroupID adds the groupID to the group add user to group params
func (o *GroupAddUserToGroupParams) WithGroupID(groupID uint64) *GroupAddUserToGroupParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the group add user to group params
func (o *GroupAddUserToGroupParams) SetGroupID(groupID uint64) {
	o.GroupID = groupID
}

// WithUserID adds the userID to the group add user to group params
func (o *GroupAddUserToGroupParams) WithUserID(userID uint64) *GroupAddUserToGroupParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the group add user to group params
func (o *GroupAddUserToGroupParams) SetUserID(userID uint64) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GroupAddUserToGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param groupId
	if err := r.SetPathParam("groupId", swag.FormatUint64(o.GroupID)); err != nil {
		return err
	}

	// path param userId
	if err := r.SetPathParam("userId", swag.FormatUint64(o.UserID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
