// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGroupAddClusterConfigurationToGroupParams creates a new GroupAddClusterConfigurationToGroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGroupAddClusterConfigurationToGroupParams() *GroupAddClusterConfigurationToGroupParams {
	return &GroupAddClusterConfigurationToGroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGroupAddClusterConfigurationToGroupParamsWithTimeout creates a new GroupAddClusterConfigurationToGroupParams object
// with the ability to set a timeout on a request.
func NewGroupAddClusterConfigurationToGroupParamsWithTimeout(timeout time.Duration) *GroupAddClusterConfigurationToGroupParams {
	return &GroupAddClusterConfigurationToGroupParams{
		timeout: timeout,
	}
}

// NewGroupAddClusterConfigurationToGroupParamsWithContext creates a new GroupAddClusterConfigurationToGroupParams object
// with the ability to set a context for a request.
func NewGroupAddClusterConfigurationToGroupParamsWithContext(ctx context.Context) *GroupAddClusterConfigurationToGroupParams {
	return &GroupAddClusterConfigurationToGroupParams{
		Context: ctx,
	}
}

// NewGroupAddClusterConfigurationToGroupParamsWithHTTPClient creates a new GroupAddClusterConfigurationToGroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewGroupAddClusterConfigurationToGroupParamsWithHTTPClient(client *http.Client) *GroupAddClusterConfigurationToGroupParams {
	return &GroupAddClusterConfigurationToGroupParams{
		HTTPClient: client,
	}
}

/* GroupAddClusterConfigurationToGroupParams contains all the parameters to send to the API endpoint
   for the group add cluster configuration to group operation.

   Typically these are written to a http.Request.
*/
type GroupAddClusterConfigurationToGroupParams struct {

	/* Body.

	   SOPS encrypted Kubernetes configuration file
	*/
	Body runtime.NamedReadCloser

	// GroupID.
	//
	// Format: uint64
	GroupID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the group add cluster configuration to group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GroupAddClusterConfigurationToGroupParams) WithDefaults() *GroupAddClusterConfigurationToGroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the group add cluster configuration to group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GroupAddClusterConfigurationToGroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the group add cluster configuration to group params
func (o *GroupAddClusterConfigurationToGroupParams) WithTimeout(timeout time.Duration) *GroupAddClusterConfigurationToGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the group add cluster configuration to group params
func (o *GroupAddClusterConfigurationToGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the group add cluster configuration to group params
func (o *GroupAddClusterConfigurationToGroupParams) WithContext(ctx context.Context) *GroupAddClusterConfigurationToGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the group add cluster configuration to group params
func (o *GroupAddClusterConfigurationToGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the group add cluster configuration to group params
func (o *GroupAddClusterConfigurationToGroupParams) WithHTTPClient(client *http.Client) *GroupAddClusterConfigurationToGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the group add cluster configuration to group params
func (o *GroupAddClusterConfigurationToGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the group add cluster configuration to group params
func (o *GroupAddClusterConfigurationToGroupParams) WithBody(body runtime.NamedReadCloser) *GroupAddClusterConfigurationToGroupParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the group add cluster configuration to group params
func (o *GroupAddClusterConfigurationToGroupParams) SetBody(body runtime.NamedReadCloser) {
	o.Body = body
}

// WithGroupID adds the groupID to the group add cluster configuration to group params
func (o *GroupAddClusterConfigurationToGroupParams) WithGroupID(groupID uint64) *GroupAddClusterConfigurationToGroupParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the group add cluster configuration to group params
func (o *GroupAddClusterConfigurationToGroupParams) SetGroupID(groupID uint64) {
	o.GroupID = groupID
}

// WriteToRequest writes these params to a swagger request
func (o *GroupAddClusterConfigurationToGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	// form file param Body
	if err := r.SetFileParam("Body", o.Body); err != nil {
		return err
	}

	// path param groupId
	if err := r.SetPathParam("groupId", swag.FormatUint64(o.GroupID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
