// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dhis2-sre/im-user/swagger/sdk/models"
)

// RefreshTokenReader is a Reader for the RefreshToken structure.
type RefreshTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RefreshTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewRefreshTokenCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRefreshTokenBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewRefreshTokenUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRefreshTokenCreated creates a RefreshTokenCreated with default headers values
func NewRefreshTokenCreated() *RefreshTokenCreated {
	return &RefreshTokenCreated{}
}

/* RefreshTokenCreated describes a response with status code 201, with default header values.

RefreshTokenCreated refresh token created
*/
type RefreshTokenCreated struct {
	Payload *models.Tokens
}

func (o *RefreshTokenCreated) Error() string {
	return fmt.Sprintf("[POST /refresh][%d] refreshTokenCreated  %+v", 201, o.Payload)
}
func (o *RefreshTokenCreated) GetPayload() *models.Tokens {
	return o.Payload
}

func (o *RefreshTokenCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Tokens)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRefreshTokenBadRequest creates a RefreshTokenBadRequest with default headers values
func NewRefreshTokenBadRequest() *RefreshTokenBadRequest {
	return &RefreshTokenBadRequest{}
}

/* RefreshTokenBadRequest describes a response with status code 400, with default header values.

RefreshTokenBadRequest refresh token bad request
*/
type RefreshTokenBadRequest struct {
}

func (o *RefreshTokenBadRequest) Error() string {
	return fmt.Sprintf("[POST /refresh][%d] refreshTokenBadRequest ", 400)
}

func (o *RefreshTokenBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRefreshTokenUnsupportedMediaType creates a RefreshTokenUnsupportedMediaType with default headers values
func NewRefreshTokenUnsupportedMediaType() *RefreshTokenUnsupportedMediaType {
	return &RefreshTokenUnsupportedMediaType{}
}

/* RefreshTokenUnsupportedMediaType describes a response with status code 415, with default header values.

RefreshTokenUnsupportedMediaType refresh token unsupported media type
*/
type RefreshTokenUnsupportedMediaType struct {
}

func (o *RefreshTokenUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[POST /refresh][%d] refreshTokenUnsupportedMediaType ", 415)
}

func (o *RefreshTokenUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
