// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dhis2-sre/im-user/swagger/sdk/models"
)

// SignInReader is a Reader for the SignIn structure.
type SignInReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SignInReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewSignInCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewSignInForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSignInNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewSignInUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSignInCreated creates a SignInCreated with default headers values
func NewSignInCreated() *SignInCreated {
	return &SignInCreated{}
}

/* SignInCreated describes a response with status code 201, with default header values.

SignInCreated sign in created
*/
type SignInCreated struct {
	Payload *models.Tokens
}

func (o *SignInCreated) Error() string {
	return fmt.Sprintf("[POST /tokens][%d] signInCreated  %+v", 201, o.Payload)
}
func (o *SignInCreated) GetPayload() *models.Tokens {
	return o.Payload
}

func (o *SignInCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Tokens)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSignInForbidden creates a SignInForbidden with default headers values
func NewSignInForbidden() *SignInForbidden {
	return &SignInForbidden{}
}

/* SignInForbidden describes a response with status code 403, with default header values.

SignInForbidden sign in forbidden
*/
type SignInForbidden struct {
}

func (o *SignInForbidden) Error() string {
	return fmt.Sprintf("[POST /tokens][%d] signInForbidden ", 403)
}

func (o *SignInForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSignInNotFound creates a SignInNotFound with default headers values
func NewSignInNotFound() *SignInNotFound {
	return &SignInNotFound{}
}

/* SignInNotFound describes a response with status code 404, with default header values.

SignInNotFound sign in not found
*/
type SignInNotFound struct {
}

func (o *SignInNotFound) Error() string {
	return fmt.Sprintf("[POST /tokens][%d] signInNotFound ", 404)
}

func (o *SignInNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSignInUnsupportedMediaType creates a SignInUnsupportedMediaType with default headers values
func NewSignInUnsupportedMediaType() *SignInUnsupportedMediaType {
	return &SignInUnsupportedMediaType{}
}

/* SignInUnsupportedMediaType describes a response with status code 415, with default header values.

SignInUnsupportedMediaType sign in unsupported media type
*/
type SignInUnsupportedMediaType struct {
}

func (o *SignInUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[POST /tokens][%d] signInUnsupportedMediaType ", 415)
}

func (o *SignInUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
