kind: Secret
apiVersion: v1
metadata:
  name: {{ include "im-user.fullname" . }}
  labels:
    {{- include "im-user.labels" . | nindent 4 }}
type: Opaque
data:
  REFRESH_TOKEN_SECRET_KEY: {{ .Values.refreshTokenSecretKey | b64enc }}

  DATABASE_HOST: {{ .Values.database.host | b64enc }}
  DATABASE_PORT: {{ .Values.database.port | b64enc }}
  DATABASE_USERNAME: {{ .Values.database.username | b64enc }}
  DATABASE_PASSWORD: {{ .Values.database.password | b64enc }}
  DATABASE_NAME: {{ .Values.database.name | b64enc }}

  REDIS_HOST: {{ .Values.redis.host | b64enc }}
  REDIS_PORT: {{ .Values.redis.port | b64enc }}

  ADMIN_USER_EMAIL: {{ .Values.adminUser.email | b64enc }}
  ADMIN_USER_PASSWORD: {{ .Values.adminUser.password | b64enc }}

  PRIVATE_KEY: {{ .Values.privateKey | b64enc }}
  PUBLIC_KEY: {{ .Values.publicKey | b64enc }}
