apiVersion: v1
kind: Service
metadata:
  name: {{ include "im-user.fullname" . }}
  labels:
    {{- include "im-user.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.debug.port }}
      targetPort: debug
      protocol: TCP
      name: debug
  selector:
    {{- include "im-user.selectorLabels" . | nindent 4 }}
