// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateGroupRequest create group request
//
// swagger:model CreateGroupRequest
type CreateGroupRequest struct {

	// hostname
	Hostname string `json:"hostname,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this create group request
func (m *CreateGroupRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create group request based on context it is used
func (m *CreateGroupRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateGroupRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateGroupRequest) UnmarshalBinary(b []byte) error {
	var res CreateGroupRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
