// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// KeyOperation key operation
//
// swagger:model KeyOperation
type KeyOperation string

// Validate validates this key operation
func (m KeyOperation) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this key operation based on context it is used
func (m KeyOperation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
