// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RefreshTokenRequest refresh token request
//
// swagger:model RefreshTokenRequest
type RefreshTokenRequest struct {

	// refresh token
	RefreshToken string `json:"refreshToken,omitempty"`
}

// Validate validates this refresh token request
func (m *RefreshTokenRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this refresh token request based on context it is used
func (m *RefreshTokenRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RefreshTokenRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RefreshTokenRequest) UnmarshalBinary(b []byte) error {
	var res RefreshTokenRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
